apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend-pod

  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-pod
    spec:
      serviceAccountName: backend-service-account
      containers:
        - name: backend-container
          image: aymenkoched02/devops-llm-bot-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: backend-config
      restartPolicy: Always
