apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-manager-binding
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: backend

subjects:
  - kind: ServiceAccount
    name: backend-service-account
    namespace: default

roleRef:
  kind: Role
  name: backend-manager
  apiGroup: rbac.authorization.k8s.io