apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-manager
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: backend

rules:
  # Core resources (ConfigMap, Service)
  - apiGroups: [""]
    resources: ["configmaps","services"]
    verbs: ["get","list","watch","create","patch","update","delete"]

  # Apps resources (Deployment)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","create","patch","update","delete"]

  # Networking resources (Ingress)
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get","list","watch","create","patch","update","delete" ]
