apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: backend

data:
  DB_HOST: "database-service"
  DB_PORT: "5432"
  DB_NAME: "service_pfa"
  DB_USERNAME: "root"
  DB_PASSWORD: "my-password"
  CLUSTER_HOST: "cloud"
  DOCKER_IMAGE: "aymenkoched02/devops-llm-bot:latest"
  INSTANCE_NAMESPACE: "default"
  INSTANCE_PORT: "3000"
  INSTANCE_REPLICAS: "1"
  SERVICE_TYPE: "ClusterIP"
  INGRESS_HOST: "bot.devops-wizard.com"
  INGRESS_NAME: "bots-ingress-service"
  OPENAI_API_KEY: ""
  OPENAI_BASE_PATH: "https://openrouter.ai/api/v1"
  CORS_ORIGIN: "http://devops-wizard.com"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_CALLBACK_URL: "http://backend.devops-wizard.com/auth/oauth/google/callback"
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GITHUB_CALLBACK_URL: "http://backend.devops-wizard.com/auth/oauth/github/callback"
  FRONT_BASE_URL: "http://devops-wizard.com"
