apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: backend

spec:
  type: ClusterIP
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
  selector:
    app: backend-pod
