apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  labels:
    app.kubernetes.io/managed-by: admin
    app: database

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
