apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: database

data:
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "my-password"