apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: bot

spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: bot-pod
