apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: bot

data:
  WEBHOOK_PROXY_URL: "https://smee.io/4QlGJj5jqVZBNKCT"
  APP_ID: "1243263"
  PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAx55vSU5DX+zItjf4tCR48I9wXR5nomZITe4q1r5ltO4szRpG\nechMc7pNYDiHeAT5IflHVxxMCOhwg2tQkhk9bzi9+EGNfyAvlOXtHdJN4iU/2WhG\nm4qhDdChYm/E3T+SPPNELTNRnrTpF7hApVT98RpqwSE6GoY5TRLsdakovnTSUti3\npd3gvDPmjJ+dzwQSiQ4T4Qf11BbB0RRPko6GxS3j11jKKv77V/7WW8f0LChyu1j4\n9ULcXN+u79ltkPuqgIeLpPkP79rPJieBkSmqu5CgjK8c8EqBbJ/dn+GxK1iEbodR\n4DjGcLy/VySnKZKj64JQSGfkkZJh+gEUrzsh6QIDAQABAoIBACpfF/IweZ6n7Sa4\nlMLwJvexCsHJTWgsW9am4lL40S/pinryw9jfylKaTghJl3/DVnp+pkT4Ta9qX0+V\n/OE2GFM+cRx8FaPRWig58e3tkPiavYXRW4NylqMPEOKLJPdtogXsASGzDfUpI30U\ncCxn8Qs3d0eNXP76VLlmdei3wl1CoDhbVBhSBgDJfLNFZzgou9odX1ZppgAIjTUK\nvf38bBxU0d051DcMHxbXhPn87YLAXeMcZ4OoHy3vi9si4KnQFTBIJ6XCdJgDJQZA\nD3792EUiFjuDLdHB1drogryxnyeGIa/Y2KwuWdKUDk1Ymk8GRRkqp5zDZhyzsqD8\nIFOgA4ECgYEA/TET80EJu3S4BZ/2xIpsRg2k8dZPfwlBcFNqGrAXMvRQeZydpm2k\nzGZMLsAa9h055lDrndrxZZAQiDrkxgwNzmgHNWpI6HGm+3XU6w01MCmuzFeWzVWP\nuiaxindtGYASq3S3eRULXOFMux8BASAMI1IJYkicNCoTYnAZW+R1iXkCgYEAydU9\ndlFR1INk4nmHxSACXlzzN/HusG9429TbmUt23ZVChAwthc9YC9BlbALE+vj6yv6Z\nseOKQgBqWFOOGYxQNCoRz75uYGKx+g0WzV95fRwd3scmTy6s34OlmpfzaITE5Vx6\nNaKByeZWXYUsujtZadiBlUDw5tG4UQgdi0Szr/ECgYEA+YGOvm2+MHuyCOD9Zetf\nDZ3OiP9/sZmmYhHhgtE621zFnUJIXUS5XTAGLR/ksdpVP3FI73Nd5Y8Vq5oV7lDc\nniYHzIyjsmSlgDI7EzMd0guRlQ9PraN+kpwk42YTHkkGnO3VDD4/x1TCr7e63qf9\nLiVe1/rj68f2+E+tvc+iQEkCgYB5RYlimEYE3NY3RjKP/UWvEUaKrPFwTepenC0+\nlJtdVJvc37xSlF0g7Byko51b91IpuoT63+9o7Pr5C2tsamSek1CUdKW5gFPUHR1A\nVUeYJtbDzwFzvmXc/yr4EqkMegocjk5X/8bgW2g1VRmk5Jg7Av4JgjW9WvHWrnuh\n/KvC4QKBgQD2dBnvIRycf8kBeRsP+DyemiYwYA15xksBfDjQ7zEtv3W7TSC8N02S\nMq2ibozGbgy7Fqp6PteyWka2xQHIluOjcr0qM1NOtmdKnYvzasjbEkJReKnFhgsU\nfn7kWWQRj3DUM9ChJJP2nwcDy43W5gDA6DQGoOvyRph5Vj8VcmtMNA==\n-----END RSA PRIVATE KEY-----\n"
  WEBHOOK_SECRET: "my-webhook-secret"
  GITHUB_CLIENT_ID: "Iv23liqvEmi6jOlSFYgf"
  GITHUB_CLIENT_SECRET: "ba2d0766251bf9f0186ba67dd5c8db7921c65ba0"
  OPENAI_API_KEY: "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"
  OPENAI_BASE_PATH: "https://openrouter.ai/api/v1"
