apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: pgadmin

data:
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "root"
