apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: default
  labels:
    app.kubernetes.io/managed-by: admin
    app: pgadmin

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: pgadmin
